services:
  - type: web
    name: judge0
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 2358
    startCommand: >
      docker run --rm -p 2358:2358 judge0/api:latest
